import { useState } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { MessageForm } from '@/components/messageForm/MessageForm'
import { MessagesList } from '@/components/messagesList/MessagesList'

export default function Home() {
  const [messages, setMessages] = useState([]);

  const onSend = (message) => {
    if(message.message) setMessages([...messages, message]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div />
        <div className={styles.chatContainer}>
          <img className={styles.logo} src='logo.png' />
          <div className={styles.chat}>
            <MessagesList selfId={1} messages={messages} />
            <MessageForm onSend={onSend} />
          </div>
        </div>
        <div />
      </main>
    </>
  )
}
